"use server"

import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { blogPosts, type BlogStatus } from "@/lib/db/schema"
import { and, desc, eq } from "drizzle-orm"
import { headers } from "next/headers"
import { revalidatePath } from "next/cache"
import { redirect } from "next/navigation"
import { del } from "@vercel/blob"
import { sanitizeHtml } from "@/lib/sanitize-html"

async function adminId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) redirect("/sign-in?next=/admin/blog"); return session.user.id }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") }
export async function listAdminPosts() { const authorId = await adminId(); return db.select().from(blogPosts).where(eq(blogPosts.authorId, authorId)).orderBy(desc(blogPosts.updatedAt)) }
export async function getAdminPost(id: string) { const authorId = await adminId(); const rows = await db.select().from(blogPosts).where(and(eq(blogPosts.id, id), eq(blogPosts.authorId, authorId))).limit(1); return rows[0] ?? null }
export async function savePost(formData: FormData) { const authorId = await adminId(); const submittedId = String(formData.get("id") ?? "").trim(); const id = submittedId || crypto.randomUUID(); const title = String(formData.get("title") ?? "").trim(); const slug = slugify(String(formData.get("slug") ?? title)); const excerpt = String(formData.get("excerpt") ?? "").trim(); const content = String(formData.get("content") ?? ""); const contentType = String(formData.get("contentType") ?? "markdown") === "html" ? "html" : "markdown"; const category = String(formData.get("category") ?? "Programming"); const tags = String(formData.get("tags") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean); const status = (String(formData.get("status") ?? "draft") === "published" ? "published" : "draft") as BlogStatus; if (!title || !excerpt || !content || !slug) throw new Error("Title, slug, excerpt, and content are required."); const slugConflict = await db.select({ id: blogPosts.id }).from(blogPosts).where(and(eq(blogPosts.slug, slug), eq(blogPosts.authorId, authorId))).limit(1); if (slugConflict[0] && slugConflict[0].id !== id) throw new Error("That slug is already used by another post. Choose a unique slug."); const values = { title, slug, excerpt, content: contentType === "html" ? sanitizeHtml(content) : content, contentType, category, tags, status, coverImage: String(formData.get("coverImage") ?? "").trim() || null, coverImageAlt: String(formData.get("coverImageAlt") ?? "").trim() || null, publishedAt: status === "published" ? new Date() : null, updatedAt: new Date(), authorId }; const previous = await db.select({ id: blogPosts.id, slug: blogPosts.slug, coverImage: blogPosts.coverImage }).from(blogPosts).where(and(eq(blogPosts.id, id), eq(blogPosts.authorId, authorId))).limit(1); if (previous.length) await db.update(blogPosts).set(values).where(and(eq(blogPosts.id, id), eq(blogPosts.authorId, authorId))); else await db.insert(blogPosts).values({ ...values, id, createdAt: new Date() }); if (previous[0]?.coverImage && previous[0].coverImage !== values.coverImage) { const stillUsed = await db.select({ id: blogPosts.id }).from(blogPosts).where(eq(blogPosts.coverImage, previous[0].coverImage)).limit(1); if (!stillUsed.length) await del(previous[0].coverImage).catch((error) => console.error("[v0] Old cover cleanup failed", error)); } revalidatePath("/blog"); revalidatePath(`/blog/${slug}`); if (previous[0]?.slug && previous[0].slug !== slug) revalidatePath(`/blog/${previous[0].slug}`); revalidatePath("/admin/blog"); redirect("/admin/blog") }
export async function deletePost(id: string) { const authorId = await adminId(); const post = await getAdminPost(id); await db.delete(blogPosts).where(and(eq(blogPosts.id, id), eq(blogPosts.authorId, authorId))); if (post?.coverImage) { const stillUsed = await db.select({ id: blogPosts.id }).from(blogPosts).where(eq(blogPosts.coverImage, post.coverImage)).limit(1); if (!stillUsed.length) await del(post.coverImage).catch((error) => console.error("[v0] Deleted cover cleanup failed", error)); } revalidatePath("/blog"); revalidatePath("/admin/blog") }
export async function togglePost(id: string, status: BlogStatus) { const authorId = await adminId(); await db.update(blogPosts).set({ status, publishedAt: status === "published" ? new Date() : null, updatedAt: new Date() }).where(and(eq(blogPosts.id, id), eq(blogPosts.authorId, authorId))); revalidatePath("/blog"); revalidatePath("/admin/blog") }
