import type { Metadata } from "next"
import Link from "next/link"
import Image from "next/image"
import { notFound } from "next/navigation"
import SiteNav from "@/components/site-nav"
import { Markdown } from "@/components/blog/markdown"
import { getPublishedPost, getRelatedPosts, readingTime } from "@/lib/blog"

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const post = await getPublishedPost((await params).slug); if (!post) return { title: "Post not found | Md Ismail" }; return { title: post.seoTitle ?? `${post.title} | Md Ismail`, description: post.seoDescription ?? post.excerpt, alternates: { canonical: `/blog/${post.slug}` }, openGraph: { type: "article", title: post.title, description: post.excerpt, images: post.ogImage ?? post.coverImage ? [post.ogImage ?? post.coverImage!] : undefined } } }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const post = await getPublishedPost((await params).slug); if (!post) notFound(); const related = (await getRelatedPosts(post)).filter((item) => item.id !== post.id).slice(0, 2); const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.excerpt, datePublished: post.publishedAt?.toISOString(), dateModified: post.updatedAt.toISOString() }; return <main className="min-h-screen overflow-x-hidden pt-24 text-white"><SiteNav /><article className="section-spacing"><div className="mx-auto max-w-4xl"><Link href="/blog" className="text-sm text-indigo-300 transition-colors hover:text-white">← Back to Blog</Link><header className="mt-10 border-b border-gray-800 pb-10"><p className="text-sm uppercase tracking-[0.2em] text-indigo-300">{post.category}</p><h1 className="mt-4 font-space-grotesk text-4xl font-bold leading-tight md:text-6xl">{post.title}</h1><p className="mt-6 max-w-3xl text-xl leading-relaxed text-gray-400">{post.excerpt}</p><div className="mt-6 flex flex-wrap gap-4 text-sm text-gray-500"><time>{new Intl.DateTimeFormat("en", { dateStyle: "long" }).format(post.publishedAt ?? post.createdAt)}</time><span>•</span><span>{readingTime(post.content)} min read</span></div></header>{post.coverImage && <div className="relative mt-10 aspect-[2/1] overflow-hidden rounded-xl border border-gray-800"><Image src={post.coverImage} alt={post.coverImageAlt || post.title} fill className="object-cover" priority sizes="(max-width: 768px) 100vw, 896px" /></div>}<div className="mt-12"><Markdown content={post.content} /></div><div className="mt-10 flex flex-wrap gap-2">{post.tags.map((tag) => <span key={tag} className="skill-tag px-3 py-1 text-xs">{tag}</span>)}</div>{related.length > 0 && <section className="mt-16 border-t border-gray-800 pt-10"><h2 className="section-header text-2xl">Related posts</h2><div className="grid gap-4 md:grid-cols-2">{related.map((item) => <Link key={item.id} href={`/blog/${item.slug}`} className="rounded-xl border border-gray-800 p-5 transition-colors hover:border-indigo-500"><p className="text-sm text-indigo-300">{item.category}</p><h3 className="mt-2 font-space-grotesk text-xl font-bold">{item.title}</h3></Link>)}</div></section>}</div></article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main> }
